name: Deploy to DO
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          
      - name: Base Deployment via SSH
        uses: appleboy/ssh-action@v0.1.4
        id: deployment
        with:
         host: ${{secrets.SSH_HOST}}
         key: ${{secrets.SSH_KEY}}
         username: ${{secrets.SSH_USERNAME}}
         script_stop: true                
         script: |
          /var/sites/apir.keyjayproductions.com/deploy.sh
          echo 'Base deployment successful to Digital Ocean'
